# Generated by Django 3.0.4 on 2020-03-05 17:52

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=500)),
                ('post_description', models.TextField()),
                ('post_image', models.ImageField(upload_to=post.models.PostModel.upload_image)),
                ('writer_name', models.CharField(max_length=200)),
                ('post_status', models.CharField(choices=[('0', 'Hold'), ('1', 'Publish')], max_length=50)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
