# Generated by Django 3.0.4 on 2020-03-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200)),
                ('plan_amount', models.FloatField()),
                ('plan_description', models.TextField()),
                ('total_queries', models.IntegerField()),
            ],
        ),
    ]
