# Generated by Django 3.0.4 on 2020-03-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyermodel',
            name='password',
            field=models.CharField(default='123', max_length=200),
        ),
    ]
