# Generated by Django 3.0.4 on 2020-03-04 18:39

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=500)),
                ('blog_description', models.TextField()),
                ('blog_image', models.ImageField(upload_to=blog.models.BlogModel.upload_image)),
                ('writer_name', models.CharField(max_length=200)),
                ('blog_status', models.CharField(choices=[('0', 'Hold'), ('1', 'Publish')], max_length=50)),
                ('blog_date', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
