# Generated by Django 3.0.4 on 2020-03-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200308_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
