# Generated by Django 3.0.4 on 2020-03-08 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_panel', '0001_initial'),
        ('user', '0003_auto_20200308_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateField()),
                ('app_time', models.TimeField()),
                ('app_desc', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('lawyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyer_panel.LawyerModel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserModel')),
            ],
        ),
    ]
