# Generated by Django 3.0.4 on 2020-03-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_appointmentsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentsmodel',
            old_name='app_date',
            new_name='appoint_date',
        ),
        migrations.RenameField(
            model_name='appointmentsmodel',
            old_name='app_desc',
            new_name='appoint_desc',
        ),
        migrations.RenameField(
            model_name='appointmentsmodel',
            old_name='app_time',
            new_name='appoint_time',
        ),
    ]
