# Generated by Django 3.0.4 on 2020-03-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200308_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsmodel',
            name='app_status',
            field=models.CharField(choices=[('0', 'waiting'), ('1', 'accept'), ('2', 'reject')], default='0', max_length=20),
        ),
    ]
