# Generated by Django 3.0.4 on 2020-03-08 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_panel', '0002_lawyermodel_password'),
        ('user', '0009_appointmentsmodel_app_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('rating', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('lawyer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lawyer_panel.LawyerModel')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.UserModel')),
            ],
        ),
    ]
